SnippetsLibraryWebApp/Controllers/SnippetsController.cs
using Duende.IdentityServer.Events;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json.Linq;
using SnippetsLibraryWebApp.Extensions;
using SnippetsLibraryWebApp.Models;
using SnippetsLibraryWebApp.Repository;
using SnippetsLibraryWebApp.Utils;
using SnippetsLibraryWebApp.ViewModels;
using System.Diagnostics;
using System.Security.Claims;

namespace SnippetsLibraryWebApp.Controllers
{
    [Authorize(AuthenticationSchemes = "CookieAuth")]
    public class SnippetsController : Controller
    {
        private readonly SnippetRepository _snippetsRepository;
        private readonly TagRepository _tagRepository;
        private readonly CategoryRepository _categoryRepository;
        private readonly ProgrammingLanguageRepository _programmingLanguageRepository;
        private readonly UserRepository _userRepository;


        public SnippetsController(
            SnippetRepository snippetRepository, 
            TagRepository tagRepository, 
            CategoryRepository categoryRepository, 
            ProgrammingLanguageRepository programmingLanguageRepository,
            UserRepository userRepository)
        {
            _snippetsRepository = snippetRepository;
            _tagRepository = tagRepository;
            _categoryRepository = categoryRepository;
            _programmingLanguageRepository = programmingLanguageRepository;
            _userRepository = userRepository;
        }

        // Дія для відкриття сторінки додавання сніпета
        [HttpGet]
        public IActionResult AddSnippet()
        {
            return View("~/Views/AddSnippet/AddSnippet.cshtml");
        }

        // Метод для пошуку авторів
        [HttpGet]
        [Route("Snippets/SearchAuthors")]
        [AllowAnonymous]
        public async Task<IActionResult> SearchAuthors(string query)
        {
            var authors = await _userRepository.GetAllAuthors(query);
            return Json(authors);
        }

        [HttpGet]
        [Route("Snippets/SearchTags")]
        [AllowAnonymous]
        public async Task<IActionResult> SearchTags(string query)
        {
            if (string.IsNullOrWhiteSpace(query))
            {
                return BadRequest("Query cannot be empty.");
            }

            var tags = await _tagRepository.SearchTagsAsync(query);
            return Json(tags);
        }

        [AllowAnonymous]
        public async Task<IActionResult> AllSnippets(int[] authorIds, int[] categoryIds, int[] tagIds, int[] languageIds, string sortOrder)
        {
            var snippets = await _snippetsRepository.GetFilteredSnippetsAsync(authorIds, categoryIds, tagIds, languageIds, sortOrder);

            // Передача всіх категорій та мов програмування для випадаючих списків
            var allTags = await _tagRepository.SearchTagsAsync();
            var allCategories = await _categoryRepository.GetAllCategoriesAsync();
            var allLanguages = await _programmingLanguageRepository.GetAllProgrammingLanguagesAsync();

            ViewBag.Tags = allTags;
            ViewBag.Categories = allCategories;
            ViewBag.ProgrammingLanguages = allLanguages;

            ViewBag.PageType = nameof(AllSnippets);

            if (Request.IsAjaxRequest())
            {
                return PartialView("_SnippetList", snippets);
            }

            return View(snippets);
        }

        // Дія для перегляду деталей сніпета
        [AllowAnonymous] // Дозволяє анонімний доступ до деталей, якщо сніпети публічні
        [HttpGet]
        [Route("Snippets/Details/{id}")]
        public async Task<IActionResult> Details(int id)
        {
            var snippet = await _snippetsRepository.GetSnippetByIdAsync(id);
            if (snippet == null)
            {
                return NotFound();
            }

            // Припустимо, що Tags та Categories вже завантажені в snippet
            return View(snippet);
        }

        // Додайте ці методи у SnippetsController

        // Метод для видалення сніпета (POST)
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("/Snippets/DeleteSnippet")]
        public async Task<IActionResult> DeleteSnippet(int ID)
        {
            var snippet = await _snippetsRepository.GetSnippetByIdAsync(ID);
            if (snippet == null)
            {
                return NotFound();
            }

            // Перевірка, чи користувач є власником сніпета
            var currentUserId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            if (snippet.AuthorID != currentUserId)
            {
                return Forbid();
            }

            // Видалення сніпета
            await _snippetsRepository.DeleteSnippetAsync(ID, currentUserId);

            return RedirectToAction("AllSnippets");
        }

        // GET: Snippets/EditSnippet/5
        [HttpGet]
        public async Task<IActionResult> EditSnippet(int id)
        {
            var snippet = await _snippetsRepository.GetSnippetByIdAsync(id);
            if (snippet == null)
            {
                return NotFound();
            }

            // Перевірка, чи користувач є власником сніпета
            var currentUserId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            if (snippet.AuthorID != currentUserId)
            {
                return Forbid();
            }

            var viewModel = new EditSnippetViewModel
            {
                ID = snippet.ID,
                Title = snippet.Title,
                ProgrammingLanguageID = snippet.ProgrammingLanguageID,
                Description = snippet.Description,
                Code = snippet.Code,
                Status = snippet.Status,
                Categories = snippet.Categories.ToList(),
                Tags = snippet.Tags.ToList(),
                ProgrammingLanguages = new SelectList(await _programmingLanguageRepository.GetAllProgrammingLanguagesAsync(), "ID", "Name", snippet.ProgrammingLanguageID),
                AllCategories = (await _categoryRepository.GetAllCategoriesAsync()).Select(c => new SelectListItem
                {
                    Value = c.ID.ToString(),
                    Text = c.Name,
                    Selected = snippet.Categories.Any(sc => sc.ID == c.ID)
                }).ToList(),
                AllTags = (await _tagRepository.SearchTagsAsync()).Select(t => new SelectListItem
                {
                    Value = t.ID.ToString(),
                    Text = t.Name,
                    Selected = snippet.Tags.Any(st => st.ID == t.ID)
                }).ToList()
            };

            return View(viewModel);
        }

        // Метод для обробки редагування сніпета
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditSnippet(EditSnippetViewModel model, int[] selectedCategories, int[] selectedTags)
        {
            if (!ModelState.IsValid)
            {
                if (model.Categories == null || model.Categories.Count() == 0)
                {
                    model.Categories = new List<CategoryModel>();

                    if(selectedCategories.Length > 0)
                    {
                        foreach(var categoryId in selectedCategories)
                        {
                            model.Categories.Add(await _categoryRepository.GetCategoryByIdAsync(categoryId));
                        }
                    }
                }

                if (model.Tags == null || model.Tags.Count() == 0)
                {
                    model.Tags = new List<TagModel>();

                    if (selectedTags.Length > 0)
                    {
                        foreach (var tagId in selectedTags)
                        {
                            model.Tags.Add(await _tagRepository.GetTagsByIdAsync(tagId));
                        }
                    }
                }
                // Повторно завантажити категорії та теги, якщо модель не валідна
                //model.Categories = (await _categoryRepository.GetCategoriesBySnippetIdAsync(model.ID)).ToList();
                //model.Tags = (await _tagRepository.GetTagsBySnippetIdAsync(model.ID)).ToList();
            }

            var existingSnippet = await _snippetsRepository.GetSnippetByIdAsync(model.ID);
            if (existingSnippet == null)
            {
                return Forbid();
            }

            var areCategoriesChanged = existingSnippet.Categories.Count() != model.Categories.Count();
            var areTagsChanged = existingSnippet.Tags.Count() != model.Tags.Count();

            for(var i = 0; i < Math.Min(existingSnippet.Categories.Count(), model.Categories.Count()); i++)
            {
                if (existingSnippet.Categories.ElementAt(i).ID != model.Categories.ElementAt(i).ID)
                {
                    areCategoriesChanged = true;
                }
            }

            for (var i = 0; i < Math.Min(existingSnippet.Tags.Count(), model.Tags.Count()); i++)
            {
                if (existingSnippet.Tags.ElementAt(i).ID != model.Tags.ElementAt(i).ID)
                {
                    areTagsChanged = true;
                }
            }

            // Оновлення полів сніпета
            existingSnippet.Title = model.Title;
            existingSnippet.Description = model.Description;
            existingSnippet.ProgrammingLanguageID = model.ProgrammingLanguageID;
            existingSnippet.Status = model.Status;
            existingSnippet.Code = model.Code;
            existingSnippet.UpdatedAt = DateTime.UtcNow;
            existingSnippet.Tags = model.Tags;
            existingSnippet.Categories = model.Categories;

            // Збереження змін

SnippetsLibraryWebApp/Views/Snippets/AllSnippets.cshtml
<!-- Views/Snippets/AllSnippets.cshtml -->
@model IEnumerable<SnippetsLibraryWebApp.Models.SnippetModel>
@{
    ViewData["Title"] = "Усі сніпети";
}

<div class="snippetss-container">
    <div class="snip-page-title-block">
        <h1>Усі сніпети</h1>
        <button class="filter-button"></button>
    </div>

    <!-- Вказівка на поточну сторінку для JavaScript -->
    <div id="currentPage" data-page="AllSnippets"></div>

    @await Html.PartialAsync("_FilterForm")

    <!-- Контейнер для сніпетів -->
    <div id="snippetsContent">
        @await Html.PartialAsync("_SnippetList", Model)
    </div>
</div>

SnippetsLibraryWebApp/Views/Snippets/Details.cshtml
@model SnippetsLibraryWebApp.Models.SnippetModel
@using SnippetsLibraryWebApp.Repository
@using System.Security.Claims
@inject ProgrammingLanguageRepository _programmingLanguageRepository
@inject UserRepository _userRepository
@inject CategoryRepository _categoryRepository
@inject TagRepository _tagRepository
@inject SnippetRepository _snippetRepository

@{
    ViewData["Title"] = "Деталі сніпета";
    var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
    bool isSaved = false;

    if (User.Identity.IsAuthenticated)
    {
        // Перевірка, чи сніпет вже збережено користувачем
        isSaved = await _snippetRepository.IsSnippedSavedByUser(int.Parse(userId), Model.ID);
    }
}

<div class="page-container">
    <h1 class="page-title">Перегляд інформації про сніпет</h1>
    <div class="form-sections-container">
        <!-- Перша частина з деталями сніпета -->
        <div class="form-details-section">
            <form asp-action="Details" method="get">
                <div class="form-group">
                    <label for="Title">Назва</label>
                    <label type="text" class="form-control" name="Title">@Model.Title</label>
                </div>

                <div class="form-group">
                    <label for="ProgrammingLanguageID">Мова програмування</label>
                    <span class="selected-category">@((await _programmingLanguageRepository.GetLanguageByIdAsync(Model.ProgrammingLanguageID)).Name)</span>
                </div>

                <div class="form-group">
                    <label>Статус</label>
                    <div class="status-toggle-group">
                        <span class="selected-category">@string.Join("", Model.Status.Substring(0, 1).ToUpper(), Model.Status.Substring(1).ToLower())</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="Description">Опис</label>
                    <label class="form-control" name="Description">@Model.Description</label>
                </div>

                <div class="form-group category-select-container">
                    <label for="Categories">Категорії</label>
                    <div class="selected-list">
                        @foreach (var category in await _categoryRepository.GetCategoriesBySnippetIdAsync(Model.ID))
                        {
                            <span class="selected-category" data-id="@category.ID">@category.Name</span>
                        }
                    </div>
                </div>

                <div class="form-group tag-select-container">
                    <label for="Tags">Теги</label>
                    <div class="selected-list">
                        @foreach (var tag in await _tagRepository.GetTagsBySnippetIdAsync(Model.ID))
                        {
                            <span class="selected-tag" data-id="@tag.ID">@tag.Name</span>
                        }
                    </div>
                </div>

@*                 <div class="form-group form-buttons">
                    <a href="@Url.Action("AllSnippets", "Snippets")" class="btn secondary-btn">Повернутися до списку</a>
                    @if(Model.AuthorID == Convert.ToInt32(userId))
                    {
                        <a href="/Snippets/EditSnippet/@Model.ID" class="btn secondary-btn">Редагувати</a>
                        <button type="button" id="deleteSnippet" class="btn secondary-btn" data-snippet-id="@Model.ID">Видалити</button>
                    }
                </div> *@
            </form>
        </div>

        <!-- Друга частина з блоком коду -->
        <div class="form-code-section">
            <div class="form-group">
                <table style="width:100%; align-self:stretch; align-content:stretch">
                    <tr>
                        <td>
                            <label for="ViewCode">Код</label>
                        </td>
                        <td style="width: 100%"></td>
                        <td style="width: 100%"></td>
                        <td style="width: 100%"></td>
                        <td style="width: 100%"></td>
                        <td style="width: 100%"></td>
                        <td style="align-content:flex-end">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <div class="form-check form-switch ms-3">
                                    <input class="form-check-input" style="display: none" type="checkbox" id="saveSnippetSwitch" @(isSaved ? "checked" : "") data-snippet-id="@Model.ID">
                                    <label class="form-check-label" for="saveSnippetSwitch">
                                        @if (isSaved)
                                        {
                                            <i class="fas fa-star text-warning"></i>
                                        }
                                        else
                                        {
                                            <i class="far fa-star text-muted"></i>
                                        }
                                    </label>
                                </div>
                            }
                        </td>
                    </tr>
                </table>
                <div class="code-editor-container">
                    <textarea id="ViewCode" name="ViewCode" class="CodeMirror" style="min-width:500px; max-width: 500px">@Html.Raw(Model.Code)</textarea>
                </div>
            </div>
        </div>
    </div>

    <div class="form-buttons edit-del-btn">
        <a href="@Url.Action("AllSnippets", "Snippets")" class="btn primary-btn">Повернутися до списку</a>
        <div>
            @if (Model.AuthorID == Convert.ToInt32(userId))
            {
                <a href="/Snippets/EditSnippet/@Model.ID" class="btn primary-btn">Редагувати</a>
                <button type="button" id="deleteSnippet" class="btn dark-btn" data-snippet-id="@Model.ID">Видалити</button>
            }
        </div>
    </div>
</div>

<!-- Підключення Font Awesome для іконок -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"/>
<!-- Підключення CodeMirror JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/codemirror.min.js"></script>
<!-- CodeMirror Основний CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.5/codemirror.min.css">
<!-- Мови CodeMirror (наприклад, JavaScript, Python, тощо) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/mode/javascript/javascript.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/mode/python/python.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/mode/xml/xml.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/mode/sql/sql.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/mode/clike/clike.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/mode/shell/shell.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/mode/php/php.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/mode/yaml/yaml.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/mode/css/css.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/mode/swift/swift.min.js"></script>
<!-- Додаткові плагіни CodeMirror (опціонально) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/addon/edit/closetag.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/addon/edit/matchbrackets.min.js"></script>

<!-- Теми CodeMirror -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/theme/monokai.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/theme/eclipse.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/theme/dracula.min.css">
<!-- Ініціалізація CodeMirror -->
<script>
    document.addEventListener("DOMContentLoaded", function () {
        var codeTextarea = document.getElementById("ViewCode");
        var language = "@((await _programmingLanguageRepository.GetLanguageByIdAsync(Model.ProgrammingLanguageID)).Name)";

        const modeMap = {
            bash: "shell",
            c: "text/x-csrc", // Режим для C
            csharp: "text/x-csharp", // Режим для C#
            cpp: "text/x-c++src", // Режим для C++
            css: "css",
            dart: "dart",
            elixir: "plaintext",
            erlang: "plaintext",
            fsharp: "plaintext",
            go: "go",
            groovy: "plaintext",
            haskell: "plaintext",
            html: "htmlmixed",
            java: "text/x-java", // Режим для Java
            javascript: "javascript",
            json: "application/json",
            julia: "plaintext",
            kotlin: "plaintext",
            lua: "lua",
            matlab: "plaintext",
            objectivec: "text/x-objectivec", // Режим для Objective-C
            other: "plaintext",
            perl: "perl",
            php: "php",
            plsql: "sql",
            powershell: "plaintext",
            python: "python",
            r: "plaintext",
            ruby: "ruby",
            rust: "rust",
            scala: "plaintext",
            shell: "shell",
            sql: "sql",
            swift: "swift",
            tsql: "sql",
            typescript: "javascript",
            vbnet: "plaintext",
            xml: "xml",
            yaml: "yaml",
        };

        language = language == "C#" ? "csharp" :
            language == "C++" ? "cpp" :
                language == "F#" ? "fsharp" :
                    language == "VB.NET" ? "vbnet" :
                        language == "PL/SQL" ? "plsql" :
                            language == "Objective-C" ? "objectivec" :
                                language == "T-SQL" ? "tsql" :
                                    language == "Visual Basic" ? "vbnet" :
                                        language == "Shell script" ? "shell" : language

        var mode = modeMap[language.toString().toLowerCase()] || "plaintext"

        var editor = CodeMirror.fromTextArea(codeTextarea, {
            lineNumbers: true,
            mode: mode,
            theme: "monokai",
            readOnly: true, // Робить редактор не редагованим
            viewportMargin: Infinity // Розгортає редактор на весь контент
        });

        // Обробка події перемикання
        var saveSwitch = document.getElementById("saveSnippetSwitch");
        saveSwitch.addEventListener("change", function () {
            var snippetId = this.getAttribute("data-snippet-id");
            var isChecked = this.checked;

            $.ajax({
                url: '@Url.Action("AddSnippetToSavedAsync", "Snippets")',
                type: 'POST',
                data: {
                    userId: '@userId',
                    snippetId: snippetId
                },
                success: function (response) {
                    if(!response.success) {
                        alert("Виникла помилка!")
                        return;
                    }

                    // Зміна стану перемикача
                    saveSwitch.checked = response.isSaved;

                    if (response.isSaved) {
                        saveSwitch.nextElementSibling.innerHTML = '<i class="fas fa-star text-warning"></i>';
                    } else {
                        saveSwitch.nextElementSibling.innerHTML = '<i class="far fa-star text-muted"></i>';
                    }
                },
                error: function () {
                    alert("Сталася помилка при обробці вашого запиту.");
                    // Відкотити стан перемикача
                    saveSwitch.checked = !isChecked;
                }
            });
        });

        $("#deleteSnippet").on("click", function () {
            debugger;
            var snippetId = this.getAttribute("data-snippet-id");

            // Підтвердження перед видаленням
            if (confirm("Ви впевнені, що хочете видалити цей сніпет?")) {
                $.ajax({
                    url: "/Snippets/DeleteSnippet",
                    type: "POST",
                    data: { ID: snippetId },
                    // contentType: "application/json; charset=utf-8",
                    headers: {
                        "RequestVerificationToken": $('input[name="__RequestVerificationToken"]').val() // CSRF-токен
                    },
                    success: function (response) {
                        // Перенаправлення на сторінку зі списком всіх сніпетів після успішного видалення
                        window.location.href = "/Snippets/AllSnippets";
                    },
                    error: function (xhr) {
                        if (xhr.status === 403) {
                            alert("Ви не маєте прав на видалення цього сніпета.");
                        } else if (xhr.status === 404) {
                            alert("Сніпет не знайдено.");
                        } else {
                            alert("Виникла помилка при спробі видалити сніпет.");
                        }
                    }
                });
            }
        });

    });
</script>

SnippetsLibraryWebApp/Views/Snippets/EditSnippet.cshtml
@using System.Security.Claims
@using SnippetsLibraryWebApp.Repository
@model SnippetsLibraryWebApp.ViewModels.EditSnippetViewModel
@inject ProgrammingLanguageRepository _programmingLanguageRepository
@{
    ViewData["Title"] = "Редагувати сніпет";
}

<div class="page-container">
    <h1 class="page-title">Редагувати сніпет</h1>
    <div class="form-sections-container">
        <!-- Перша частина з деталями сніпета -->
        <div class="form-details-section">
            <form id="editSnippetForm" asp-action="EditSnippet" method="post">
                @Html.AntiForgeryToken()
                <input type="hidden" name="ID" value="@Model.ID" />

                <!-- Назва -->
                <div class="form-group">
                    <label for="Title">Назва <span class="required">*</span></label>
                    <textarea type="text" class="form-control" id="Title" name="Title" placeholder="Придумайте лаконічну назву..." required>@Model.Title</textarea>
                </div>

                <!-- Мова Програмування -->
                <div class="form-group">
                    <label for="ProgrammingLanguageID">Мова програмування <span class="required">*</span></label>
                    @Html.DropDownListFor(model => model.ProgrammingLanguageID, Model.ProgrammingLanguages, "-- Оберіть мову --", new { @class = "select-search", required = "required" })
                </div>

                <!-- Статус -->
                <div class="form-group">
                    <label>Статус <span class="required">*</span></label>
                    <div class="status-toggle-group">
                        <input type="radio" id="statusPublic" name="Status" value="Public" required @(Model.Status.Equals("Public", StringComparison.OrdinalIgnoreCase) ? "checked=\"checked\"" : "") />
                        <label for="statusPublic" class="toggle-label">Public</label>
                        <input type="radio" id="statusPrivate" name="Status" value="Private" required @(Model.Status.Equals("Private", StringComparison.OrdinalIgnoreCase) ? "checked=\"checked\"" : "") />
                        <label for="statusPrivate" class="toggle-label">Private</label>
                    </div>
                </div>

                <!-- Опис -->
                <div class="form-group">
                    <label for="Description">Опис</label>
                    <textarea class="form-control" id="Description" name="Description" placeholder="Опишіть, що виконує даний сніпет...">@Model.Description</textarea>
                </div>

                <!-- Категорії -->
                <div class="form-group category-select-container">
                    <label for="Categories">Категорії</label>
                    <div id="categoryDropdown" class="custom-dropdown">
                        <span class="dropdown-placeholder">-- Оберіть до 3-х категорій --</span>
                        <div id="dropdownCategoryList" class="dropdown-content">
                            @foreach (var category in Model.AllCategories)
                            {
                                <label class="checkbox-label">
                                    <input type="checkbox" class="category-checkbox" name="selectedCategories" value="@category.Value" @(category.Selected ? "checked=\"checked\"" : "") />
                                    @category.Text
                                </label>
                            }
                        </div>
                    </div>
                    <div id="selectedCategories" class="selected-list">
                        @foreach (var category in Model.Categories)
                        {
                            <span class="selected-category" data-id="@category.ID">@category.Name <span class="remove-category">×</span></span>
                        }
                    </div>
                </div>

                <!-- Теги -->
                <div class="form-group tag-select-container">
                    <label for="Tags">Теги</label>
                    <div id="tagDropdown" class="custom-dropdown">
                        <span class="dropdown-placeholder">--Оберіть теги--</span>
                        <div id="dropdownTagList" class="dropdown-content">
                            @foreach (var tag in Model.AllTags)
                            {
                                <label class="checkbox-label">
                                    <input type="checkbox" class="tag-checkbox" name="selectedTags" value="@tag.Value" @(tag.Selected ? "checked=\"checked\"" : "") />
                                    @tag.Text
                                </label>
                            }
                        </div>
                    </div>
                    <div id="selectedTags" class="selected-list">
                        @foreach (var tag in Model.Tags)
                        {
                            <span class="selected-tag" data-id="@tag.ID">@tag.Name <span class="remove-tag">×</span></span>
                        }
                    </div>
                </div>

                <!-- Додавання Нових Тегів -->
                <div class="form-group">
                    <div class="add-tag-container">
                        <input type="text" class="form-control add-tag-field" id="addTag" name="addTag" placeholder="Додайте власний тег за потреби..." />
                        <button type="button" id="addTagBtn" class="secondary-btn">Додати</button>
                    </div>
                </div>

                <!-- Кнопки -->
                <div class="form-group form-buttons">
                    <button type="submit" id="saveSnippet" class="btn primary-btn">Зберегти</button>
                    <a href="@Url.Action("AllSnippets", "Snippets")" class="btn secondary-btn">Відмінити</a>
                </div>
            </form>

            <script>
                var userID = '@int.Parse(User.FindFirst(ClaimTypes.NameIdentifier).Value)';
                var languageName = '@((await _programmingLanguageRepository.GetLanguageByIdAsync(Model.ProgrammingLanguageID)).Name)';
            </script>
        </div>

        <!-- Друга частина з блоком коду -->
        <div class="form-code-section">
            <div class="form-group">
                <label for="Code">Код <span class="required">*</span></label>
                <div class="code-editor-container">
                    <textarea id="Code" name="Code" class="CodeMirror" required style="min-width:500px; max-width: 500px">@Html.Raw(Model.Code)</textarea>
                </div>
            </div>
        </div>

    </div>


</div>

SnippetsLibraryWebApp/Views/Snippets/FavoriteSnippets.cshtml
<!-- Views/Snippets/FavoriteSnippets.cshtml -->
@model IEnumerable<SnippetsLibraryWebApp.Models.SnippetModel>
@{
    ViewData["Title"] = "Обрані сніпети";
}

<div class="snippetss-container">
    <div class="snip-page-title-block">
        <h1>Обрані сніпети</h1>
        <button class="filter-button"></button>
    </div>

    <!-- Вказівка на поточну сторінку для JavaScript -->
    <div id="currentPage" data-page="FavoriteSnippets"></div>

    @await Html.PartialAsync("_FilterForm")

    <!-- Контейнер для сніпетів -->
    <div id="snippetsContent">
        @await Html.PartialAsync("_SnippetList", Model)
    </div>
</div>